# By default, this docker-compose file will start bili-discovery
#
# Some directives have been left commented out so they serve as an
# example for more advanced use.

# start on a single node:
#
#    docker-compose up
#
# start on docker swarm:
#
#    docker swarm init (if you haven't already)
#    docker stack deploy -c docker-compose.yaml mybilicluster
#

version: "3.5"

services:
  discovery1:
    build:
      context: .
      target: discovery
      dockerfile: Dockerfile.bili
    container_name: discovery-7171
    ports:
      - 7171:7171
    restart: always
    command:
      - -conf=/opt/discovery-idc1-1.toml
    networks:
      intranet_network:
        ipv4_address: 192.168.110.2

  discovery2:
    build:
      context: .
      target: discovery
      dockerfile: Dockerfile.bili
    container_name: discovery-7172
    ports:
      - 7172:7172
    restart: always
    command:
      - -conf=/opt/discovery-idc1-2.toml
    networks:
      intranet_network:
        ipv4_address: 192.168.110.3

  discovery3:
    build:
      context: .
      target: discovery
      dockerfile: Dockerfile.bili
    container_name: discovery-80
    ports:
      - 80:80
    restart: always
    command:
      - -conf=/opt/discovery-idc1-3.toml
    networks:
      intranet_network:
        ipv4_address: 192.168.110.8

  config:
    build:
      context: .
      target: config
      dockerfile: Dockerfile.bili
    container_name: config
    extra_hosts:
      - "bvc-nerve.bilibili.co:172.18.21.10"
      - "api.bilibili.co:192.168.110.8"
      - "discovery.bilibili.co:192.168.110.8"
    ports:
      - 8171:8171
    depends_on:
      - config_redis
      - config_mysql
    restart: always
    command:
      - -conf=/opt/config-service-example.toml
    networks:
      intranet_network:
        ipv4_address: 192.168.110.4

  config_redis:
    image: "redis"
    container_name: config_redis
    restart: always
    networks:
      intranet_network:
        ipv4_address: 192.168.110.5

  config_mysql:
    image: mysql
    restart: always
    container_name: config_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    ports:
      - 3308:3308
    networks:
      intranet_network:
        ipv4_address: 192.168.110.6

  proxy_nginx: 
    build:
      context: .
      dockerfile: Nginx
    restart: always
    depends_on: 
      - config_redis
    ports:
      - "8088:80"
    container_name: proxy_nginx
    networks:
      intranet_network: 
        ipv4_address: 192.168.110.7

networks:
  intranet_network:
    name: "intranet_network"
    driver: "bridge"
    ipam:
      config:
        - subnet: 192.168.110.0/24