# By default, this docker-compose file will start bili-discovery
#
# Some directives have been left commented out so they serve as an
# example for more advanced use.

# start on a single node:
#
#    docker-compose up
#
# start on docker swarm:
#
#    docker swarm init (if you haven't already)
#    docker stack deploy -c docker-compose.yaml mybilicluster
#

version: "3.5"

services:
  discovery1:
    build:
      context: .
      target: discovery
      dockerfile: Dockerfile.bili
    container_name: discovery-7171
    ports:
      - 7171:7171
    restart: always
    command:
      - -conf=/opt/discovery-idc1-1.toml
    networks:
      intranet_network:
        ipv4_address: 192.168.110.2

  discovery2:
    build:
      context: .
      target: discovery
      dockerfile: Dockerfile.bili
    container_name: discovery-7172
    ports:
      - 7172:7172
    restart: always
    command:
      - -conf=/opt/discovery-idc1-2.toml
    networks:
      intranet_network:
        ipv4_address: 192.168.110.3

  # config:
  #   build:
  #     context: .
  #     target: config
  #     dockerfile: Dockerfile.bili
  #   container_name: config
  #   ports:
  #     - 8171:8171
  #   restart: always
  #   command:
  #     - -conf=/opt/config-service-example.toml
  #   networks:
  #     intranet_network:
  #       ipv4_address: 192.168.110.3

networks:
  intranet_network:
    name: "intranet_network"
    driver: "bridge"
    ipam:
      config:
        - subnet: 192.168.110.0/24